services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"  # Mapeia a porta 3306 do contêiner para a 3307 no host
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
